name: PHP Quality Assurance
on: [push, pull_request]
jobs:

    Unit_Tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.0', '7.1', '7.2', '7.3', '7.4']
                prefer:
                  - "lowest"
                  - "highest"
                ignore-platform:
                  - ""
                experimental:
                  - false
                include:
                  - php: "8.0"
                    prefer: "highest"
                    ignore-platform: "--ignore-platform-reqs"
                    experimental: true
                  - php: "8.1"
                      prefer: "highest"
                      ignore-platform: "--ignore-platform-reqs"
                      experimental: true

        continue-on-error: ${{ matrix.experimental }}

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP version
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}

            - name: Check syntax error in sources
              run: find ./src/ ./tests/src/ ./tests/cases/ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l

            - name: Remove Psalm before tests, to prevent installation conflicts
              run: composer.phar remove vimeo/psalm --no-update

            - name: Install dependencies
              uses: "ramsey/composer-install@v1"
              with:
                dependency-versions: ${{ matrix.prefer }}
                composer-options: ${{ matrix.ignore-platform }}

            - name: Migrate PHPUnit config for PHPUnit 9
              if: ${{ (matrix.php >= 7.3) && (matrix.prefer == 'highest') }}
              run: ./vendor/bin/phpunit --migrate-configuration

            - name: Run unit tests
              run: ./vendor/bin/phpunit

    Static_Analisys:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Setup PHP version
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.4'

        - name: Install dependencies
          uses: "ramsey/composer-install@v1"

        - name: Check code styles
          run: ./vendor/bin/phpcs

        - name: Check cross-version PHP compatibility
          run: composer phpcompat

        - name: Check Psalm
          run: ./vendor/bin/psalm
