name: Sync Development Branch

on:
  push:
    branches:
      - 'version/2'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.DEPLOYBOT_SSH_PRIVATE_KEY }}

            - name: Set up Git
              run: |
                  git config --global user.email "${{ secrets.DEPLOYBOT_EMAIL }}"
                  git config --global user.name "${{ secrets.DEPLOYBOT_USER }}"

            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.DEPLOYBOT_API_TOKEN }}
                  ssh-key: ${{ secrets.DEPLOYBOT_SSH_PRIVATE_KEY }}

            - name: Merge target branch
              run: |
                git checkout development
                git merge ${{ github.ref_name }}
                git push
